### ISSUE TITLE
Deprecation warning in node 12.2.0

### ISSUE THREAD

**Issue by SagePtr** [keymetrics/event-loop-inspector#8]
```
[DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
warn DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
    at Object.extractSocket (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/utils.js:33:44)
    at /usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:39:17
    at Array.forEach (<anonymous>)
    at Object.dump (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:22:42)
    at Timeout._onTimeout (/usr/local/lib/node_modules/pm2/node_modules/@pm2/io/build/main/src/features/actions.js:18:96)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```
PM2 depends on your module, so please fix it to support Node 12.x without deprecation warnings.

**Comment by vincentvalletvoodoo** [comment]
@SagePtr 

I will check that soon. It seems they deprecated the access to private properties but fortunately, they had public methods to retrieve headers.

**Comment by wallet77** [comment]
@SagePtr 

I made all the changes and I was ready to publish but it looks like I do not have rights anymore on this repo.
What a shame!
You should try to ping Keymetrics to ask them to work on this issue. They're the only ones I guess who can commit on this repo.

**Comment by PassTheMayo** [comment]
@wallet77 In the mean time, couldn't you fork and simply just publish to npm? You still own that part of this repository. Once Keymetrics notices the deprecation warning, they could just add the fix to this repository themselves.

**Comment by ejdaly** [comment]
Have created a PR
https://github.com/keymetrics/event-loop-inspector/pull/9

**Comment by Unitech** [comment]
https://github.com/keymetrics/pm2-io-apm/commit/4578a447c71a16e1350814b65c1088f450dbd3e8
